server:
  debug: true

http_server:
  port: "8000"

grpc_server:
  port: "8001"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "zura123456"
  db_name: "zura"

log:
  level: info
  filename: "./logs/logic.log"
  max_age: 7
  max_size: 10
  max_backups: 5
  compress: false

comet_server:
  host: "127.0.0.1"
  port: "9001"

session:
  heartbeat_interval: -1