debug: true

http_port: "9000"
grpc_port: "9001"

logic:
  host: "127.0.0.1"
  port: "8001"

log:
  level: info
  filename: "./logs/comet.log"
  max_age: 7
  max_size: 10
  max_backups: 5
  compress: false

session:
  heartbeat_interval: 30